# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9c35ef257edb4031e1b4bcc034da0c0e501fe8ec75d09c24d5ec49cdc828030b270bbd1f932855a0769765378979b938291ba232597994960a594cc7e3a89c

test:
  secret_key_base: 685d1a0731007ba8d36bcbd3482d226f35d0106faf07d0391db4560fac3906fcdd7aaa4eec5e951789ad6b5a64bec7fe9279cf8e491397fb002200831a0554d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
